import { Task } from '@/Types';

export const tasks: Task[] = [
  {
    id: '1',
    title: 'Design Kanban layout',
    description: 'Define column layout, spacing, and hierarchy',
    status: 'todo',
    priority: 'high',
  },
  {
    id: '2',
    title: 'Choose color palette',
    description: 'Pick neutral base colors and accent colors',
    status: 'todo',
    priority: 'medium',
  },
  {
    id: '3',
    title: 'Create Column component',
    description: 'Reusable column with config-based styles',
    status: 'doing',
    priority: 'high',
  },
  {
    id: '4',
    title: 'Implement Card UI',
    description: 'Card layout with title, description, and icons',
    status: 'doing',
    priority: 'medium',
  },
  {
    id: '5',
    title: 'Set up mock data',
    description: 'Create static task array for development',
    status: 'done',
    priority: 'low',
  },
  {
    id: '6',
    title: 'Add priority indicator',
    description: 'Visual indicator for task priority',
    status: 'todo',
    priority: 'medium',
  },
  {
    id: '7',
    title: 'Mobile-first layout',
    description: 'Stack columns vertically on small screens',
    status: 'todo',
    priority: 'high',
  },
  {
    id: '8',
    title: 'Dark mode support',
    description: 'Ensure colors and contrast work in dark theme',
    status: 'doing',
    priority: 'medium',
  },
  {
    id: '9',
    title: 'Persist board to localStorage',
    description: 'Save and restore tasks on reload',
    status: 'todo',
    priority: 'high',
  },
  {
    id: '10',
    title: 'Create task types',
    description: 'Define Task, Status, and Priority types',
    status: 'done',
    priority: 'low',
  },
  {
    id: '11',
    title: 'Column header icons',
    description: 'Add status icons to column headers',
    status: 'done',
    priority: 'low',
  },
  {
    id: '12',
    title: 'Filter by priority',
    description: 'Allow filtering tasks by priority level',
    status: 'doing',
    priority: 'high',
  },
  {
    id: '13',
    title: 'Add empty column state',
    description: 'Show placeholder when no tasks exist',
    status: 'todo',
    priority: 'low',
  },
  {
    id: '14',
    title: 'Refactor to useReducer',
    description: 'Centralize task logic and actions',
    status: 'doing',
    priority: 'high',
  },
  {
    id: '15',
    title: 'Prepare for drag and drop',
    description: 'Add IDs and structure for dnd-kit',
    status: 'todo',
    priority: 'medium',
  },
  {
    id: '16',
    title: 'Improve card spacing',
    description: 'Adjust padding and margins for readability',
    status: 'done',
    priority: 'low',
  },
  {
    id: '17',
    title: 'Add card hover states',
    description: 'Visual feedback on hover and drag',
    status: 'todo',
    priority: 'medium',
  },
  {
    id: '18',
    title: 'Board header UI',
    description: 'Title, filters, and actions in header',
    status: 'doing',
    priority: 'medium',
  },
  {
    id: '19',
    title: 'Accessibility pass',
    description: 'Check contrast and keyboard navigation',
    status: 'todo',
    priority: 'low',
  },
  {
    id: '20',
    title: 'Final UI polish',
    description: 'Small tweaks before publishing',
    status: 'done',
    priority: 'low',
  },
];
